[project]
name = "postgres-fastapi-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.3",
    "fastapi[standard]>=0.128.0",
    "psycopg[binary]>=3.3.2",
    "sqlmodel>=0.0.32",
]
